name: "MonoGame Builder"
author: "akaadream"
description: "Build your MonoGame projects with this action. Useful for build checks."
inputs:
  dotnet-version:
    description: ".NET version used to build the project."
    required: false
    default: "8.0.x"
  solution-path:
    description: "Path to the `.sln`. Used to restore NuGet packages from."
    required: true
  csproj-path:
    description: >
      Path to the `.csproj` to build with.
      This is passed to `msbuild` to initiate the build.
    required: true
  build-os:
    description: "The OS target of the build: Defaults is `win-x64`"
    required: true
    default: "win-x64"

runs:
  using: "composite"
  steps:
    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ inputs.dotnet-version }}

    - name: Install MGCB
      run: dotnet tool install -g dotnet-mgcb
      shell: pwsh

    - name: Install dependencies
      run: nuget restore "${{ inputs.solution-path }}"
      shell: pwsh

    - name: Build project
      run: |
        dotnet publish ${{ inputs.csproj-path }} `
          -c Release `
          -r ${{ inputs.build-os }} `
          /p:PublishReadyToRun=false `
          /p:TieredCompilation=false `
          --self-contained
      shell: pwsh

branding:
  icon: "check-circle"
  color: "green"
